module.exports = [
	{
		"id": "4wE5n1nh64nuzMmcV4a6",
		"porcentajeSeguroMercancia": 0.02,
		"minimoSeguroMercancia": 0,
		"minimaComision": 0,
		"tipoEnvio": "PAGO DESTINO",
		"precioBase": 8900,
		"pesoMin": 1,
		"tipoCotizacion": "URBAN",
		"precioKgAdicional": 0,
		"constanteComision": 0,
		"id_usuario_firebase": "_DEFAULT",
		"id_user": "_DEFAULT",
		"pesoMax": 4,
		"constanteSeguroMercancia": 0,
		"porcentajeComision": 0
	},
	{
		"id": "8AXyvMRWByC1ZTgfxKbs",
		"minimaComision": 0,
		"minimoSeguroMercancia": 0,
		"constanteSeguroMercancia": 0,
		"tipoEnvio": "PAGO DESTINO",
		"precioBase": 12900,
		"porcentajeSeguroMercancia": 0.02,
		"porcentajeComision": 0,
		"tipoCotizacion": "NACIONAL",
		"id_usuario_firebase": "_DEFAULT",
		"constanteComision": 0,
		"pesoMax": 4,
		"id_user": "_DEFAULT",
		"precioKgAdicional": 0,
		"pesoMin": 1
	},
	{
		"minimoSeguroMercancia": 0,
		"id_user": "_DEFAULT",
		"porcentajeSeguroMercancia": 0.02,
		"tipoEnvio": "CONVENCIONAL",
		"pesoMin": 1,
		"minimaComision": 0,
		"tipoCotizacion": "URBAN",
		"id_usuario_firebase": "_DEFAULT",
		"constanteComision": 0,
		"precioKgAdicional": 0,
		"porcentajeComision": 0,
		"constanteSeguroMercancia": 0,
		"pesoMax": 4,
		"id": "WWcz4FbNgLPq7GndjBKm",
		"precioBase": 8900
	},
	{
		"precioKgAdicional": 0,
		"minimoSeguroMercancia": 0,
		"constanteComision": 0,
		"id_usuario_firebase": "_DEFAULT",
		"precioBase": 8000,
		"id": "ZHOeITkdrZUIS19ZKI9F",
		"tipoEnvio": "PAGO CONTRAENTREGA",
		"porcentajeSeguroMercancia": 0,
		"minimaComision": 0,
		"constanteSeguroMercancia": 0,
		"porcentajeComision": 0.04,
		"tipoCotizacion": "URBAN",
		"pesoMax": 4,
		"id_user": "_DEFAULT",
		"pesoMin": 1
	},
	{
		"tipoEnvio": "CONVENCIONAL",
		"porcentajeComision": 0,
		"precioKgAdicional": 0,
		"id_usuario_firebase": "_DEFAULT",
		"precioBase": 12900,
		"minimaComision": 0,
		"id_user": "_DEFAULT",
		"minimoSeguroMercancia": 0,
		"constanteSeguroMercancia": 0,
		"pesoMax": 4,
		"porcentajeSeguroMercancia": 0.02,
		"constanteComision": 0,
		"pesoMin": 1,
		"tipoCotizacion": "NACIONAL",
		"id": "jsz5UY9byb4fNeETGz5P"
	},
	{
		"minimoSeguroMercancia": 0,
		"precioKgAdicional": 0,
		"precioBase": 13900,
		"constanteComision": 0,
		"pesoMin": 1,
		"porcentajeComision": 0.029,
		"pesoMax": 4,
		"id_usuario_firebase": "_DEFAULT",
		"id": "wGdGAvJPcJLPXbhD70Ia",
		"minimaComision": 0,
		"tipoCotizacion": "NACIONAL",
		"tipoEnvio": "PAGO CONTRAENTREGA",
		"porcentajeSeguroMercancia": 0,
		"constanteSeguroMercancia": 0,
		"id_user": "_DEFAULT"
	}
]