module.exports = [
	{
		"precioKgAdicional": 0,
		"tipoCotizacion": "NACIONAL",
		"id": "8AXyvMRWByC1ZTgfxKbs",
		"porcentajeSeguroMercancia": 0.02,
		"minimoSeguroMercancia": 0,
		"tipoEnvio": "PAGO DESTINO",
		"constanteComision": 0,
		"constanteSeguroMercancia": 0,
		"porcentajeComision": 0,
		"pesoMax": 3,
		"pesoMin": 1,
		"precioBase": 12900,
		"id_user": "_DEFAULT",
		"minimaComision": 0
	},
	{
		"precioBase": 6300,
		"tipoCotizacion": "URBAN",
		"id_user": "_DEFAULT",
		"porcentajeComision": 0.02,
		"pesoMin": 1,
		"constanteComision": 0,
		"id": "ZHOeITkdrZUIS19ZKI9F",
		"minimoSeguroMercancia": 0,
		"porcentajeSeguroMercancia": 0.02,
		"constanteSeguroMercancia": 0,
		"minimaComision": 0,
		"pesoMax": 3,
		"precioKgAdicional": 0
	},
	{
		"constanteSeguroMercancia": 0,
		"tipoCotizacion": "NACIONAL",
		"minimaComision": 0,
		"porcentajeComision": 0,
		"precioKgAdicional": 0,
		"minimoSeguroMercancia": 0,
		"pesoMax": 3,
		"constanteComision": 0,
		"precioBase": 12900,
		"tipoEnvio": "CONVENCIONAL",
		"id_user": "_DEFAULT",
		"pesoMin": 1,
		"id": "jsz5UY9byb4fNeETGz5P",
		"porcentajeSeguroMercancia": 0.02
	},
	{
		"minimoSeguroMercancia": 0,
		"tipoEnvio": "PAGO CONTRAENTREGA",
		"constanteComision": 0,
		"pesoMin": 1,
		"tipoCotizacion": "NACIONAL",
		"id_user": "_DEFAULT",
		"porcentajeSeguroMercancia": 0,
		"precioBase": 13900,
		"precioKgAdicional": 0,
		"constanteSeguroMercancia": 0,
		"porcentajeComision": 0.029,
		"id": "wGdGAvJPcJLPXbhD70Ia",
		"minimaComision": 0,
		"pesoMax": 3
	}
]