const COD_SERVIENTREGA = "SERVIENTREGA";
const COD_INTERRAPIDISIMO = "INTERRAPIDISIMO";
const COD_ENVIA = "ENVIA";
const COD_TCC = "TCC";
const COD_COORDINADORA = "COORDINADORA";

const CONTRAENTREGA = "PAGO DESTINO";
const PAGO_CONTRAENTREGA = "PAGO CONTRAENTREGA";
const CONVENCIONAL = "CONVENCIONAL";

const codigosTransportadora = [COD_SERVIENTREGA, COD_INTERRAPIDISIMO, COD_ENVIA, COD_TCC, COD_COORDINADORA];

// Lista de todos los errores narutalmente devueltos y controlados

module.exports = {
    codigosTransportadora,
    COD_COORDINADORA,
    COD_ENVIA,
    COD_INTERRAPIDISIMO,
    COD_SERVIENTREGA, COD_TCC,
    CONTRAENTREGA,
    PAGO_CONTRAENTREGA,
    CONVENCIONAL
}